AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  RdsUserPassword:
    Type: String
    NoEcho: true
    Description: "Password for the RdsUser"
Resources:
  RdsUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "RdsUser"
      Groups:
        - !Ref RdsGroup
      LoginProfile:
        Password: !Ref RdsUserPassword
        PasswordResetRequired: false
      Tags:
        - Key: "Department"
          Value: "DBAdmins"
  RdsGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "RdsAccessGroup"

  RdsPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "RdsAccessPolicy"
      Groups:
        - !Ref RdsGroup
      PolicyDocument: |
                        {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Action": [
                                          "rds:DescribeDBInstances",
                                          "rds:DescribeDBClusters",
                                          "rds:DescribeGlobalClusters"
                                  ],
                                  "Resource": "*"
                              },
                              
                              {
                                  "Effect": "Allow",
                                  "Action": [
                                      "rds:RebootDBInstance",
                                      "rds:StartDBInstance",
                                      "rds:StopDBInstance"
                                  ],
                                  "Resource": "*",
                                  "Condition": {
                                      "StringEquals": {
                                          "aws:PrincipalTag/Department": "DBAdmins",
                                          "rds:db-tag/Environment": "Production"
                                      }
                                  }
                              }
                            ]
                        }
        

        

      
      